apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open-webui
spec:
  serviceName: "open-webui"
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      volumes:
      - name: open-webui-data
        persistentVolumeClaim:
          claimName: open-webui-data-pvc
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama:11434"
        # - name: WEBUI_BASE_URL
        #   value: "/"
        volumeMounts:
        - name: open-webui-data
          mountPath: /app/backend/data
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1000
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10