apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open-webui
spec:
  serviceName: "open-webui"
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      volumes:
      - name: open-webui-data
        persistentVolumeClaim:
          claimName: open-webui-data-pvc
      containers:
      - name: open-webui
        image: richardjoseph1/open-webui:0da84bf6c235e3d670213c3688ca04eb41d08237
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama:11434"
        # - name: WEBUI_BASE_URL
        #   value: "/"
        volumeMounts:
        - name: open-webui-data
          mountPath: /app/backend/data
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 35
          periodSeconds: 30
        
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10