apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Rule 2: OpenWebUI at the Root
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 8080